<a href="https://colab.research.google.com/github/irfan7210/Python_practice/blob/main/irfan_Numpy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Python Numpy Assignment**

In [ ]:
import numpy as np

**Q1) Write a python program to count the frequency of unique values in NumPy array.**

In [ ]:
ini_array = np.array([10, 20, 5, 10, 8, 20, 8, 9])


# Get a tuple of unique values
# and their frequency in
# numpy array
dic = {}
for i in ini_array:
  if i in dic:
    dic[i] += 1
  else:
    dic[i] = 1

# print unique values array
print('\nprinting unique values in array')
# print(dic.values())
for key, val in dic.items():
  print(key, end = ' ')

# print frequency array
print('\nPrinting frequencies')
for key, val in dic.items():
  print(val, end = ' ')

printing unique values in array
10 20 5 8 9
Printing frequencies
2 2 1 2 1

**Q2) Write a program to add a border of zeros around the existing array.**

For example,
If you have the below array:

[[ 1.  1.  1.  1.]                                                          
 [ 1.  1.  1.  1.]                                                          
 [ 1.  1.  1.  1.]]

 The resultant array should be: (zeros on the border and 1s within it)

 [[ 0.  0.  0.  0.  0.  0.]                                                  
 [ 0.  1.  1.  1.  1.  0.]                                                  
 [ 0.  1.  1.  1.  1.  0.]                                                  
 [ 0.  1.  1.  1.  1.  0.]                                                  
 [ 0.  0.  0.  0.  0.  0.]]

In [ ]:
#mention the size of array that you want to fit with zero sorounded
n = 5
# Create NumPy arrays filled with ones
arr = np.ones((n,n))
# arr = arr.reshape(n,n)
#creating additional array with zeros, not we need to add one at befor and one after, so the size would be n+2
zero_arr = np.zeros((n+2,n+2))

#now palce the array starting at index 1
zero_arr[1:-1, 1:-1] = arr

print(zero_arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

**Q3) Write a program for creating an integer array with values belonging to the range 10 and 60**

In [ ]:
# Write your code here
start_val = 10
last_val = 60
arr = np.arange(start_val, last_val + 1)    #1 is added as the range will not inclued the last item
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60]

**Q4) Write a program to repeat each of the elements five times for a given array.**

In [ ]:
# Create Sample NumPy Array
arr = np.array(['i', 'love', 'NumPy', 'AND', 'almabetter'], dtype=str)
# for i in arr:
#   print(i*5)

# print(arr)
arr = np.repeat(arr, 5)
print(arr)

iiiii
lovelovelovelovelove
NumPyNumPyNumPyNumPyNumPy
ANDANDANDANDAND
almabetteralmabetteralmabetteralmabetteralmabetter
['i' 'love' 'NumPy' 'AND' 'almabetter']
['i' 'i' 'i' 'i' 'i' 'love' 'love' 'love' 'love' 'love' 'NumPy' 'NumPy'
 'NumPy' 'NumPy' 'NumPy' 'AND' 'AND' 'AND' 'AND' 'AND' 'almabetter'
 'almabetter' 'almabetter' 'almabetter' 'almabetter']

**Q5) Write a program for inserting space between characters of all elements in a NumPy array.**

In [ ]:
# Create Sample NumPy Array
arr = np.array(['i', 'love', 'NumPy', 'AND', 'almabetter'], dtype=str)
arr = np.char.join(" ", arr)
print(arr)

['i' 'l o v e' 'N u m P y' 'A N D' 'a l m a b e t t e r']

**Q6) Write a program to transform elements of a given string to a numeric string of 10 digits by making all the elements of a given string to a numeric string of 8 digits with zeros on the left.**

In [ ]:
# Create Sample NumPy array
arr = np.array(['22', '9', '1234', '567', '89102'], dtype=str)
arr = np.char.zfill(arr, 8)
print(arr)

['00000022' '00000009' '00001234' '00000567' '00089102']

**Q7) Write a program to convert a string element to uppercase, lowercase, capitalise the first letter, title-case and swapcase of a given NumPy array.**

In [ ]:
# Create Sample NumPy array
arr = np.array(['i', 'love', 'NumPy', 'AND', 'almabetter'], dtype=str)
lis = []
for i in arr:
  lis.append(i.lower())
lower_arr = np.array(lis)
print('Lower case')
print(lower_arr)

lis=[]
for i in arr:
  lis.append(i.upper())
upper_arr = np.array(lis)
print('upper case')
print(upper_arr)

lis=[]
for i in arr:
  lis.append(i.capitalize())
capitalized_arr = np.array(lis)
print('capitalized')
print(capitalized_arr)

Lower case
['i' 'love' 'numpy' 'and' 'almabetter']
upper case
['I' 'LOVE' 'NUMPY' 'AND' 'ALMABETTER']
capitalized
['I' 'Love' 'Numpy' 'And' 'Almabetter']

**Q8) Write a python program to create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers?**

In [ ]:
# Write your code here
arr = np.arange(5,(5+30),3)   #10 digits with step size 3 would be 30, so adding 5 to it to get raing upto last possible value
print(arr)

#complex way to get dynamic outputs
step = 3
starting_val = 5
number_of_items = 10
print(f'\nPrinting for dynamic inputs step = {step}, starting value = {starting_val}, number of items = {number_of_items}.')
arr_dynamic = np.arange(starting_val, (starting_val+step*number_of_items) , step)
print(arr_dynamic)

[ 5  8 11 14 17 20 23 26 29 32]

Printing for dynamic inputs step = 3, starting value = 5, number of items = 10.
[ 5  8 11 14 17 20 23 26 29 32]

**Q9) Write a python program to find the index of 5th repetition of number 1 in x.**

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [ ]:
# Write your code here
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
lis = np.where(x == 1)[0]
print(lis[4])
print('Dynamic code the index of 5th repetition of number 1 in x')
item_to_find = 1
position = 5
lis = np.where(x == item_to_find)[0]
print(f'position is: {lis[position-1]}')

8
Dynamic code the index of 5th repetition of number 1 in x
position is: 8

**Q10) Write a python program to subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.**

a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])

b_1d = np.array([1,2,3])

In [ ]:
# Write your code here
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])

b_1d = np.array([1,2,3])

# Input
res = a_2d - b_1d[:, np.newaxis]
print(res)
# https://www.edureka.co/community/66684/how-does-numpy-newaxis-work-and-when-to-use-it

[[2 2 2]
 [2 2 2]
 [2 2 2]]

**Q11) Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.**

**Input:**

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

**Desired Output:**

array([2, 5])

where, 2 and 5 are the positions of peak values 7 and 6.

In [ ]:
# Write your code here

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
lis = np.where((a[1:-1] > a[:-2]) & (a[1:-1] > a[2:]))[0] + 1
print(lis)

[2 5]

**Q12) Compute the euclidean distance between two arrays a and b.**

In [ ]:
# Input
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
distance = np.linalg.norm(a - b)
print(distance)


# own logic
diff = b - a
sq_diff = diff**2
sum_of_squares = np.sum(sq_diff)
dist = np.sqrt(sum_of_squares)
print(dist)

6.708203932499369
6.708203932499369

**Q13) Compute the min-by-max for each row for given 2d numpy array.**

In [ ]:
# Write your code here
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

# Input
min_max = np.min(a, axis=1)/np.max(a,axis=1 ) # axis = 1 for row wise operation
print('min by max')
print(min_max)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
min by max
[0.22222222 0.11111111 0.11111111]

**Q14) From the array a, replace all values greater than 30 to 30 and less than 10 to 10.**

**Input:**

np.random.seed(100)

a = np.random.uniform(1,50, 20)

In [ ]:
# Write your code here
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print('before')
print(a)
res1 = a_clipped = np.clip(a, 10, 30)
res = np.where(a > 30, 30, np.where(a < 10, 10, a))
print('using clip')
print(res1)
print('using where')
print(res)

before
[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
using clip
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]
using where
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]

###**Python iris Case Study**

Import the iris dataset keeping the text intact.

In [ ]:
import pandas as pd

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
df= pd.read_csv(url, names=names)
print(df.head(3))

   sepallength  sepalwidth  petallength  petalwidth      species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa

**Q15) Extract the text column species from the 1D iris imported in previous question.**

In [ ]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

# Solution:
species_column = df['species']
print(species_column)

(150,)
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

<ipython-input-80-06458c73c8a8>:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

**Q16) Convert the 1D iris to 2D array iris_2d by omitting the species text field.**

In [ ]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# Solution:
iris_2d = np.vstack((df['sepallength'], df['sepalwidth'], df['petallength'], df['petalwidth'])).T
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]

<ipython-input-84-023f0fa84de2>:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

**Q17) Find the mean, median, standard deviation of iris's sepallength (1st column)**

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print('mean by python')
print(sepallength.mean())
print('median')
print(np.median(sepallength))
print('mean by np')
print(np.mean(sepallength))
print('STD')
print(np.std(sepallength))
# Solution

mean by python
5.843333333333334
median
5.8
mean by np
5.843333333333334
STD
0.8253012917851409

**Q18) Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.**

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
min_val = np.min(sepallength)
max_val = np.max(sepallength)
normalized = (sepallength - min_val) / (max_val - min_val)
print(normalized)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333333 0.5        0.41666667 0.19444444 0.36111111 0.38888889
 0.38888889 0.52777778 0.22222222 0.38888889 0.55555556 0.41666667
 0.77777778 0.55555556 0.61111111 0.91666667 0.16666667 0.83333333
 0.66666667 0.80555556 0.61111111 0.58333333 0.69444444 0.38888889
 0.41666667 0.58333333 0.61111111 0.94444444 0.94444444 0.47222222
 0.72222222 0.36111111 0.94444444 0.55555556 0.66666667 0.80555556
 0.52777778 0.5        0.58333333 0.80555556 0.86111111 1.
 0.58333333 0.55555556 0.5        0.94444444 0.55555556 0.58333333
 0.47222222 0.72222222 0.66666667 0.72222222 0.41666667 0.69444444
 0.66666667 0.66666667 0.55555556 0.61111111 0.52777778 0.44444444]

**Q19) Find the 5th and 95th percentile of iris's sepallength**

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
per_5 = np.percentile(sepallength, 5)
per_95 = np.percentile(sepallength, 95)
print(f'5th percentile = {per_5}\n95th percentile = {per_95}')

5th percentile = 4.6
95th percentile = 7.254999999999998

**Q20) Insert np.nan values at 20 random positions in iris_2d dataset**

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
row,col = iris_2d.shape
random_rows = np.random.randint(0, row, 20)
random_cols = np.random.randint(0, col, 20)

# Insert np.nan values at the random positions
iris_2d[random_rows, random_cols] = np.nan

print(iris_2d)

[[b'5.1' b'3.5' b'1.4' b'0.2' nan]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' nan]
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' nan]
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' nan]
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.3' b'1.7' b'0.5' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.0' b'1.6' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.6' b'0.4' b'Iris-setosa']
 [b'5.2' b'3.5' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.2' b'3.4' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.2' b'4.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.5' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.0' b'3.2' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.5' b'3.5' nan b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' nan b'Iris-setosa']
 [b'5.1' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.5' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'5.0' nan b'1.6' b'0.6' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.9' b'0.4' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.3' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.3' b'1.4' b'0.2' b'Iris-setosa']
 [b'7.0' b'3.2' b'4.7' nan b'Iris-versicolor']
 [b'6.4' b'3.2' b'4.5' b'1.5' b'Iris-versicolor']
 [b'6.9' b'3.1' b'4.9' b'1.5' b'Iris-versicolor']
 [b'5.5' b'2.3' b'4.0' b'1.3' nan]
 [b'6.5' b'2.8' b'4.6' b'1.5' b'Iris-versicolor']
 [b'5.7' b'2.8' b'4.5' b'1.3' b'Iris-versicolor']
 [b'6.3' b'3.3' b'4.7' b'1.6' b'Iris-versicolor']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'6.6' b'2.9' b'4.6' nan b'Iris-versicolor']
 [b'5.2' b'2.7' b'3.9' b'1.4' b'Iris-versicolor']
 [b'5.0' b'2.0' b'3.5' b'1.0' b'Iris-versicolor']
 [b'5.9' b'3.0' b'4.2' b'1.5' b'Iris-versicolor']
 [b'6.0' b'2.2' b'4.0' b'1.0' b'Iris-versicolor']
 [b'6.1' b'2.9' b'4.7' b'1.4' b'Iris-versicolor']
 [b'5.6' b'2.9' b'3.6' b'1.3' b'Iris-versicolor']
 [b'6.7' b'3.1' b'4.4' b'1.4' b'Iris-versicolor']
 [b'5.6' b'3.0' b'4.5' b'1.5' b'Iris-versicolor']
 [b'5.8' b'2.7' b'4.1' b'1.0' b'Iris-versicolor']
 [b'6.2' b'2.2' b'4.5' b'1.5' b'Iris-versicolor']
 [b'5.6' b'2.5' b'3.9' b'1.1' b'Iris-versicolor']
 [b'5.9' b'3.2' b'4.8' b'1.8' b'Iris-versicolor']
 [b'6.1' b'2.8' nan b'1.3' b'Iris-versicolor']
 [b'6.3' b'2.5' b'4.9' b'1.5' b'Iris-versicolor']
 [b'6.1' b'2.8' b'4.7' b'1.2' b'Iris-versicolor']
 [b'6.4' b'2.9' b'4.3' b'1.3' b'Iris-versicolor']
 [b'6.6' b'3.0' b'4.4' b'1.4' b'Iris-versicolor']
 [b'6.8' nan b'4.8' b'1.4' b'Iris-versicolor']
 [b'6.7' b'3.0' b'5.0' b'1.7' b'Iris-versicolor']
 [b'6.0' b'2.9' b'4.5' b'1.5' b'Iris-versicolor']
 [b'5.7' b'2.6' b'3.5' b'1.0' b'Iris-versicolor']
 [b'5.5' b'2.4' b'3.8' b'1.1' b'Iris-versicolor']
 [b'5.5' b'2.4' b'3.7' b'1.0' b'Iris-versicolor']
 [b'5.8' b'2.7' b'3.9' b'1.2' b'Iris-versicolor']
 [b'6.0' b'2.7' b'5.1' b'1.6' b'Iris-versicolor']
 [b'5.4' nan b'4.5' b'1.5' b'Iris-versicolor']
 [b'6.0' b'3.4' b'4.5' b'1.6' b'Iris-versicolor']
 [b'6.7' b'3.1' b'4.7' b'1.5' b'Iris-versicolor']
 [b'6.3' b'2.3' b'4.4' b'1.3' b'Iris-versicolor']
 [b'5.6' b'3.0' b'4.1' b'1.3' b'Iris-versicolor']
 [b'5.5' b'2.5' b'4.0' b'1.3' b'Iris-versicolor']
 [b'5.5' b'2.6' b'4.4' b'1.2' b'Iris-versicolor']
 [b'6.1' b'3.0' b'4.6' b'1.4' b'Iris-versicolor']
 [b'5.8' b'2.6' b'4.0' b'1.2' b'Iris-versicolor']
 [b'5.0' b'2.3' b'3.3' b'1.0' b'Iris-versicolor']
 [b'5.6' b'2.7' b'4.2' nan b'Iris-versicolor']
 [b'5.7' b'3.0' nan b'1.2' b'Iris-versicolor']
 [b'5.7' b'2.9' b'4.2' b'1.3' b'Iris-versicolor']
 [b'6.2' b'2.9' b'4.3' b'1.3' b'Iris-versicolor']
 [b'5.1' b'2.5' b'3.0' b'1.1' b'Iris-versicolor']
 [b'5.7' b'2.8' b'4.1' b'1.3' b'Iris-versicolor']
 [b'6.3' b'3.3' b'6.0' b'2.5' b'Iris-virginica']
 [b'5.8' b'2.7' b'5.1' b'1.9' b'Iris-virginica']
 [nan b'3.0' b'5.9' b'2.1' b'Iris-virginica']
 [b'6.3' b'2.9' b'5.6' b'1.8' b'Iris-virginica']
 [b'6.5' b'3.0' b'5.8' b'2.2' b'Iris-virginica']
 [b'7.6' b'3.0' b'6.6' b'2.1' b'Iris-virginica']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'7.3' b'2.9' b'6.3' b'1.8' b'Iris-virginica']
 [b'6.7' b'2.5' b'5.8' b'1.8' b'Iris-virginica']
 [b'7.2' b'3.6' b'6.1' b'2.5' b'Iris-virginica']
 [b'6.5' b'3.2' b'5.1' b'2.0' b'Iris-virginica']
 [b'6.4' b'2.7' b'5.3' b'1.9' b'Iris-virginica']
 [b'6.8' b'3.0' b'5.5' b'2.1' b'Iris-virginica']
 [b'5.7' b'2.5' b'5.0' b'2.0' b'Iris-virginica']
 [b'5.8' b'2.8' b'5.1' nan b'Iris-virginica']
 [b'6.4' b'3.2' b'5.3' b'2.3' b'Iris-virginica']
 [b'6.5' b'3.0' b'5.5' b'1.8' b'Iris-virginica']
 [b'7.7' b'3.8' b'6.7' b'2.2' b'Iris-virginica']
 [b'7.7' b'2.6' b'6.9' b'2.3' b'Iris-virginica']
 [nan b'2.2' b'5.0' b'1.5' b'Iris-virginica']
 [b'6.9' b'3.2' b'5.7' b'2.3' b'Iris-virginica']
 [b'5.6' b'2.8' b'4.9' b'2.0' b'Iris-virginica']
 [b'7.7' b'2.8' b'6.7' b'2.0' b'Iris-virginica']
 [b'6.3' b'2.7' b'4.9' b'1.8' b'Iris-virginica']
 [b'6.7' b'3.3' b'5.7' b'2.1' b'Iris-virginica']
 [b'7.2' b'3.2' b'6.0' b'1.8' b'Iris-virginica']
 [b'6.2' b'2.8' b'4.8' b'1.8' b'Iris-virginica']
 [b'6.1' b'3.0' b'4.9' b'1.8' b'Iris-virginica']
 [b'6.4' b'2.8' b'5.6' b'2.1' b'Iris-virginica']
 [b'7.2' b'3.0' b'5.8' b'1.6' b'Iris-virginica']
 [b'7.4' b'2.8' b'6.1' b'1.9' b'Iris-virginica']
 [b'7.9' b'3.8' b'6.4' b'2.0' b'Iris-virginica']
 [b'6.4' b'2.8' b'5.6' b'2.2' b'Iris-virginica']
 [b'6.3' b'2.8' b'5.1' b'1.5' b'Iris-virginica']
 [b'6.1' b'2.6' b'5.6' b'1.4' b'Iris-virginica']
 [b'7.7' b'3.0' b'6.1' b'2.3' b'Iris-virginica']
 [b'6.3' b'3.4' b'5.6' b'2.4' b'Iris-virginica']
 [b'6.4' b'3.1' b'5.5' b'1.8' b'Iris-virginica']
 [b'6.0' b'3.0' b'4.8' b'1.8' b'Iris-virginica']
 [b'6.9' b'3.1' b'5.4' b'2.1' b'Iris-virginica']
 [b'6.7' b'3.1' b'5.6' b'2.4' b'Iris-virginica']
 [b'6.9' b'3.1' b'5.1' b'2.3' b'Iris-virginica']
 [b'5.8' b'2.7' b'5.1' b'1.9' b'Iris-virginica']
 [b'6.8' b'3.2' b'5.9' b'2.3' b'Iris-virginica']
 [b'6.7' b'3.3' b'5.7' b'2.5' b'Iris-virginica']
 [b'6.7' b'3.0' b'5.2' b'2.3' b'Iris-virginica']
 [b'6.3' b'2.5' b'5.0' b'1.9' b'Iris-virginica']
 [b'6.5' b'3.0' nan b'2.0' b'Iris-virginica']
 [b'6.2' b'3.4' b'5.4' b'2.3' b'Iris-virginica']
 [b'5.9' b'3.0' b'5.1' b'1.8' b'Iris-virginica']]

**Q21) Find the number and position of missing values in iris_2d's sepallength (1st column)**

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution

**Q22) Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0**

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution

**Q23) Select the rows of iris_2d that does not have any nan value.**

In [ ]:
import numpy as np

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
rows_without_nan = iris_2d[~np.isnan(iris_2d).any(axis=1)]
# rows_without_nan

**Q24) Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d**

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution 1
sepal_length = iris_2d[:, 0]
petal_length = iris_2d[:, 2]
corr = np.corrcoef(sepal_length, petal_length)[0, 1]

print("Correlation between Sepal Length and Petal Length:", corr)

Correlation between Sepal Length and Petal Length: nan

nan

**Q25) What is the value of second longest petallength of species setosa?**

In [ ]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
petal_length = iris[:, 2].astype(float)
species = iris[:, 4]

# Filter data for species "setosa"
setosa_petal_length = petal_length[species == b'Iris-setosa']

# Sort the Petal Lengths in ascending order
setosa_petal_length_sorted = np.sort(setosa_petal_length)

# Get the second longest Petal Length value
second_longest_petal_length = setosa_petal_length_sorted[-2]

print("Second longest Petal Length of species setosa:", second_longest_petal_length)

Second longest Petal Length of species setosa: 1.9

## **Python Pandas Assignment**

In [ ]:
import pandas as pd

### **Python COVID-19 Case Study**

Coronavirus disease 2019 (COVID-19) is an infectious disease caused by severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). The disease was first identified in 2019 in Wuhan, China, and has since spread globally, resulting in the 2019–20 coronavirus pandemic. Common symptoms include fever, cough and shortness of breath. Muscle pain, sputum production and sore throat are less common. The rate of deaths per number of diagnosed cases is on average 3.4%, ranging from 0.2% in those less than 20 to approximately 15% in those over 80 years old.

**Data Source (Date wise) :** 2019 Novel Coronavirus COVID-19 (2019-nCoV) Data Repository by Johns Hopkins CSSE

**Data Source:** https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports

**File naming convention**

MM-DD-YYYY.csv in UTC.

**Field description**

**Province/State:** China - province name; US/Canada/Australia/ - city name, state/province name; Others - name of the event (e.g., "Diamond Princess" cruise ship); other countries - blank.

**Country/Region:** country/region name conforming to WHO (will be updated).

**Last Update:** MM/DD/YYYY HH:mm (24 hour format, in UTC).

**Confirmed:** the number of confirmed cases. For Hubei Province: from Feb 13 (GMT +8), we report both clinically diagnosed and lab-confirmed cases. For lab-confirmed cases only (Before Feb 17), please refer to who_covid_19_situation_reports. For Italy, diagnosis standard might be changed since Feb 27 to "slow the growth of new case numbers." (Source)

**Deaths:** the number of deaths.

**Recovered:** the number of recovered cases.

**Update frequency**

Files after Feb 1 (UTC): once a day around 23:59 (UTC).

Files on and before Feb 1 (UTC): the last updated files before 23:59 (UTC).

Using above dataset we have created some exercises on COVID-19 (Spread of the novel coronavirus, Analysis, Visualization, Prediction & Comparisons

**Q26) Write a Python program to display first 5 rows from COVID-19 dataset. Also print the dataset information and check the missing values.**

In [ ]:
# Write your code here
covid_data= pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv')

covid_data.head(5)

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,China,2020-03-17T11:53:10,67799,3111,56003,30.9756,112.2707
1,NaN,Italy,2020-03-17T18:33:02,31506,2503,2941,41.8719,12.5674
2,NaN,Iran,2020-03-17T15:13:09,16169,988,5389,32.4279,53.6880
3,NaN,Spain,2020-03-17T20:53:02,11748,533,1028,40.4637,-3.7492
4,NaN,Germany,2020-03-17T18:53:02,9257,24,67,51.1657,10.4515

**Q27) Write a Python program to get the latest number of confirmed, deaths, recovered and active cases of Novel Coronavirus (COVID-19) Country wise.**

In [ ]:
# Write your code here
import pandas as pd

covid_data = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv')

# Group the data by Country/Region and get the latest numbers for each country
latest_data = covid_data.groupby('Country/Region').agg({
    'Confirmed': 'sum',
    'Deaths': 'sum',
    'Recovered': 'sum'
}).reset_index()

# Calculate active cases by subtracting deaths and recovered from confirmed cases
latest_data['Active'] = latest_data['Confirmed'] - latest_data['Deaths'] - latest_data['Recovered']

# Display the latest data
print("Latest COVID-19 Data (as of 03-17-2020):\n")
print(latest_data[['Country/Region', 'Confirmed', 'Deaths', 'Recovered', 'Active']])

Latest COVID-19 Data (as of 03-17-2020):

                     Country/Region  Confirmed  Deaths  Recovered  Active
0                       Afghanistan         26       0          1      25
1                           Albania         55       1          0      54
2                           Algeria         60       4         12      44
3                           Andorra         39       0          1      38
4                        Antarctica          0       0          0       0
..                              ...        ...     ...        ...     ...
163                      Uzbekistan         10       0          0      10
164                       Venezuela         33       0          0      33
165                         Vietnam         66       0         16      50
166            Winter Olympics 2022          0       0          0       0
167  occupied Palestinian territory          0       0          0       0

[168 rows x 5 columns]

**Q28) Write a Python program to get the latest number of confirmed deaths and recovered people of Novel Coronavirus (COVID-19) cases Country/Region - Province/State wise.**

In [ ]:
# Write your code here
# Group the data by 'Country/Region' and 'Province/State' and get the latest data for each region
latest_data = covid_data.groupby(['Country/Region', 'Province/State']).agg({
    'Confirmed': 'sum',
    'Deaths': 'sum',
    'Recovered': 'sum'
}).reset_index()

# Print the latest data
print("Latest number of COVID-19 cases country/region - province/state wise:")
latest_data

Latest number of COVID-19 cases country/region - province/state wise:

,Country/Region,Province/State,Confirmed,Deaths,Recovered
0,Australia,Australian Capital Territory,2,0,0
1,Australia,From Diamond Princess,0,0,0
2,Australia,New South Wales,210,4,4
3,Australia,Northern Territory,1,0,0
4,Australia,Queensland,78,0,8
...,...,...,...,...,...
149,United Kingdom,Northern Ireland,0,0,0
150,United Kingdom,Pitcairn Islands,0,0,0
151,United Kingdom,Scotland,0,11,0
152,United Kingdom,Unknown,1950,2,52
153,United Kingdom,Wales,0,5,0

**Q29) Write a Python program to get the Chinese province wise cases of confirmed, deaths and recovered cases of Novel Coronavirus (COVID-19).**

In [ ]:
# Write your code here
# Filter data for China
china_data = covid_data[covid_data['Country/Region'] == 'China']

# Group the data by 'Province/State' and get the latest data for each province
chinese_province_data = china_data.groupby('Province/State').agg({
    'Confirmed': 'sum',
    'Deaths': 'sum',
    'Recovered': 'sum'
}).reset_index()

# Print the Chinese province-wise data
print("Chinese province-wise cases of COVID-19:")
chinese_province_data

Chinese province-wise cases of COVID-19:

    Province/State  Confirmed  Deaths  Recovered
0            Anhui        990       6        984
1          Beijing        456       8        369
2        Chongqing        576       6        570
3           Fujian        296       1        295
4            Gansu        133       2         91
5        Guangdong       1364       8       1307
6          Guangxi        253       2        248
7          Guizhou        147       2        144
8           Hainan        168       6        161
9            Hebei        318       6        310
10    Heilongjiang        482      13        456
11           Henan       1273      22       1250
12       Hong Kong        162       4         88
13           Hubei      67799    3111      56003
14           Hunan       1018       4       1014
15  Inner Mongolia         75       1         73
16         Jiangsu        631       0        631
17         Jiangxi        935       1        934
18           Jilin         93       1         92
19        Liaoning        125       1        120
20           Macau         12       0         10
21         Ningxia         75       0         75
22         Qinghai         18       0         18
23         Shaanxi        246       3        236
24        Shandong        761       7        746
25        Shanghai        358       3        325
26          Shanxi        133       0        133
27         Sichuan        540       3        520
28         Tianjin        136       3        133
29           Tibet          1       0          1
30         Unknown          0       0          0
31        Xinjiang         76       3         73
32          Yunnan        176       2        172
33        Zhejiang       1232       1       1216

**Q30) Write a Python program to get the latest country wise deaths cases of Novel Coronavirus (COVID-19).**

In [ ]:
# Write your code here
# Group the data by 'Country/Region' and get the latest death cases for each country
latest_death_cases = covid_data.groupby('Country/Region')['Deaths'].sum().reset_index()

# Print the latest country-wise death cases
print("Latest country-wise deaths cases of COVID-19:")
latest_death_cases

Latest country-wise deaths cases of COVID-19:

                     Country/Region  Deaths
0                       Afghanistan       0
1                           Albania       1
2                           Algeria       4
3                           Andorra       0
4                        Antarctica       0
..                              ...     ...
163                      Uzbekistan       0
164                       Venezuela       0
165                         Vietnam       0
166            Winter Olympics 2022       0
167  occupied Palestinian territory       0

[168 rows x 2 columns]

**Q31) Write a Python program to list countries with no cases of Novel Coronavirus (COVID-19) recovered.**

In [ ]:
# Write your code here
# Group the data by 'Country/Region' and get the latest recovered cases for each country
latest_recovered_cases = covid_data.groupby('Country/Region')['Recovered'].sum().reset_index()

# Filter countries with zero recovered cases
countries_with_no_recovered_cases = latest_recovered_cases[latest_recovered_cases['Recovered'] == 0]

# Print the list of countries with no cases of recovered
print("Countries with no cases of recovered from COVID-19:")
countries_with_no_recovered_cases

Countries with no cases of recovered from COVID-19:

                     Country/Region  Recovered
1                           Albania          0
4                        Antarctica          0
5               Antigua and Barbuda          0
8                             Aruba          0
14                         Barbados          0
..                              ...        ...
162                         Uruguay          0
163                      Uzbekistan          0
164                       Venezuela          0
166            Winter Olympics 2022          0
167  occupied Palestinian territory          0

[90 rows x 2 columns]

**Q32) Write a Python program to list countries with all cases of Novel Coronavirus (COVID-19) died.**

In [ ]:
# Write your code here
# Group the data by 'Country/Region' and get the latest death and confirmed cases for each country
latest_cases = covid_data.groupby('Country/Region').agg({
    'Confirmed': 'sum',
    'Deaths': 'sum'
}).reset_index()

# Filter countries with all cases resulting in death
countries_with_all_deaths = latest_cases[latest_cases['Confirmed'] == latest_cases['Deaths']].reset_index()

# Print the list of countries with all cases resulted in death
print("Countries with all cases resulted in death from COVID-19:")
countries_with_all_deaths

Countries with all cases resulted in death from COVID-19:

    index                  Country/Region  Confirmed  Deaths
0       4                      Antarctica          0       0
1      61                        Guernsey          0       0
2      77                          Jersey          0       0
3      81                        Kiribati          0       0
4      82                    Korea, North          0       0
5      90                       Lithuania          0       0
6      92                        Malaysia          0       0
7     105                           Nauru          0       0
8     114                           Palau          0       0
9     121                     Puerto Rico          0       0
10    123           Republic of the Congo          0       0
11    142                           Sudan          1       1
12    143            Summer Olympics 2020          0       0
13    153                           Tonga          0       0
14    157                          Tuvalu          0       0
15    166            Winter Olympics 2022          0       0
16    167  occupied Palestinian territory          0       0

**Q33) Write a Python program to list countries with all cases of Novel Coronavirus (COVID-19) recovered.**

In [ ]:
# Write your code here
# Group the data by 'Country/Region' and get the latest recovered and confirmed cases for each country
latest_cases = covid_data.groupby('Country/Region').agg({
    'Confirmed': 'sum',
    'Recovered': 'sum'
}).reset_index()

# Filter countries with all cases recovered
countries_with_all_recovered = latest_cases[latest_cases['Confirmed'] == latest_cases['Recovered']].reset_index()

# Print the list of countries with all cases recovered from COVID-19
print("Countries with all cases recovered from COVID-19:")
countries_with_all_recovered

Countries with all cases recovered from COVID-19:

    index                  Country/Region  Confirmed  Recovered
0       4                      Antarctica          0          0
1      61                        Guernsey          0          0
2      77                          Jersey          0          0
3      81                        Kiribati          0          0
4      82                    Korea, North          0          0
5      92                        Malaysia          0          0
6     105                           Nauru          0          0
7     106                           Nepal          1          1
8     114                           Palau          0          0
9     121                     Puerto Rico          0          0
10    123           Republic of the Congo          0          0
11    143            Summer Olympics 2020          0          0
12    153                           Tonga          0          0
13    157                          Tuvalu          0          0
14    166            Winter Olympics 2022          0          0
15    167  occupied Palestinian territory          0          0

**Q34) Write a Python program to get the top 10 countries data (Last Update, Country/Region, Confirmed, Deaths, Recovered) of Novel Coronavirus (COVID-19).**

In [ ]:
# Write your code here
# Sort the data by 'Confirmed' cases in descending order
sorted_data = covid_data.sort_values(by='Confirmed', ascending=False)

# Get the top 10 rows
top_10_countries_data = sorted_data.head(10)

# Select the desired columns (Last Update, Country/Region, Confirmed, Deaths, Recovered)
top_10_countries_data = top_10_countries_data[['Last Update', 'Country/Region', 'Confirmed', 'Deaths', 'Recovered']]

# Print the top 10 countries' data
print("Top 10 countries' data of COVID-19:")
top_10_countries_data

Top 10 countries' data of COVID-19:

           Last Update  Country/Region  Confirmed  Deaths  Recovered
0  2020-03-17T11:53:10           China      67799    3111      56003
1  2020-03-17T18:33:02           Italy      31506    2503       2941
2  2020-03-17T15:13:09            Iran      16169     988       5389
3  2020-03-17T20:53:02           Spain      11748     533       1028
4  2020-03-17T18:53:02         Germany       9257      24         67
5  2020-03-17T10:33:03    Korea, South       8320      81       1407
6  2020-03-17T19:13:08          France       7652     148         12
7  2020-03-17T16:33:04     Switzerland       2700      40          4
8  2020-03-17T15:13:09  United Kingdom       1950       2         52
9  2020-03-17T22:53:03              US       1706      13          0

###**Python 'Diamond' Case Study**

**Diamonds:**

This classic dataset contains the prices and other attributes of almost 54,000 diamonds. It's a great dataset for beginners learning to work with data analysis and visualization.

![python pandas.JPG]()

In [ ]:
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print(diamonds)

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

**Q35) Write a Pandas program to read a dataset from diamonds DataFrame and modify the default columns values and print the first 6 rows.**

In [ ]:
# Write your code here
diamonds.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

**Q36) Write a Pandas program to create a new 'Quality -color' Series (use bracket notation to define the Series name) of the diamonds DataFrame.**

In [ ]:
# Write your code here
# Write your code here
# Create a new 'Quality - color' Series using bracket notation
diamonds['Quality - color'] = diamonds['cut'] + ' - ' + diamonds['color']

# Print the DataFrame with the new 'Quality - color' Series
diamonds

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality - color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal - E
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium - E
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good - E
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium - I
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good - J
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal - D
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good - D
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good - D
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium - H
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal - D

**Q37) Write a Pandas program to sort the 'cut' Series in ascending order (returns a Series) of diamonds Dataframe.**

In [ ]:
# Write your code here
# Sort the 'cut' Series in ascending order and print the first 6 rows
sorted_diamonds = diamonds.sort_values(by='cut')
sorted_diamonds

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality - color
3850,1.01,Fair,F,SI2,64.8,55.0,3477,6.37,6.26,4.10,Fair - F
51464,1.20,Fair,G,I1,66.6,57.0,2376,6.57,6.50,4.34,Fair - G
51466,0.90,Fair,G,SI2,65.4,57.0,2376,6.01,5.97,3.98,Fair - G
10237,1.26,Fair,D,SI2,64.5,59.0,4746,6.75,6.71,4.34,Fair - D
10760,1.01,Fair,E,SI1,69.5,55.0,4853,6.00,5.94,4.15,Fair - E
...,...,...,...,...,...,...,...,...,...,...,...
7402,0.33,Very Good,G,VS2,62.8,54.0,579,4.40,4.42,2.77,Very Good - G
43101,0.57,Very Good,E,SI2,58.8,57.3,1384,5.42,5.46,3.21,Very Good - E
16893,1.00,Very Good,G,VS2,62.2,58.0,6743,6.35,6.39,3.96,Very Good - G
16898,1.00,Very Good,D,VS2,59.6,60.0,6745,6.52,6.57,3.90,Very Good - D
21164,1.00,Very Good,E,VVS2,61.7,55.0,9324,6.38,6.42,3.95,Very Good - E

**Q38) Write a Pandas program to filter the DataFrame rows to only show carat weight at least 0.3.**

In [ ]:
# Write your code here
# Filter the DataFrame to show carat weight at least 0.3
filtered_diamonds = diamonds[diamonds['carat'] >= 0.3]

# Print the filtered DataFrame
filtered_diamonds

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality - color
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good - J
10,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73,Good - J
13,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71,Ideal - J
15,0.32,Premium,E,I1,60.9,58.0,345,4.38,4.42,2.68,Premium - E
16,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68,Ideal - I
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal - D
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good - D
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good - D
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium - H
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal - D

**Q39) Write a Pandas program to find the diamonds that are with a Fair or Good or Premium.**

In [ ]:
# Write your code here
# Define the list of cut categories to filter
cut_categories = ['Fair', 'Good', 'Premium']

# Filter the DataFrame to show diamonds with cut categories 'Fair', 'Good', or 'Premium'
filtered_diamonds = diamonds[diamonds['cut'].isin(cut_categories)]

# Print the filtered DataFrame
filtered_diamonds

,carat,cut,color,clarity,depth,table,price,x,y,z,Quality - color
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium - E
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good - E
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium - I
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good - J
8,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49,Fair - E
...,...,...,...,...,...,...,...,...,...,...,...
53930,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49,Premium - E
53931,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43,Premium - F
53934,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58,Premium - D
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good - D
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium - H

**Q40) Write a Pandas program to calculate the mean of price for each cut of diamonds DataFrame.**

In [ ]:
# Write your code here
# Write your code here
# Calculate the mean price for each cut
mean_price_by_cut = diamonds.groupby('cut')['price'].mean().reset_index()

# Print the mean price for each cut in DataFrame format
mean_price_by_cut

         cut        price
0       Fair  4358.757764
1       Good  3928.864452
2      Ideal  3457.541970
3    Premium  4584.257704
4  Very Good  3981.759891

**Q41) Write a Pandas program to display percentages of each value of cut series occurs in diamonds DataFrame.**

In [ ]:
# Write your code here
# Calculate the percentages of each value in the 'cut' series
cut_percentages = (diamonds['cut'].value_counts(normalize=True) * 100).reset_index()

# Rename the columns
cut_percentages.columns = ['cut', 'percentage']

# Print the percentages of each value in the 'cut' series
cut_percentages

         cut  percentage
0      Ideal   39.953652
1    Premium   25.567297
2  Very Good   22.398962
3       Good    9.095291
4       Fair    2.984798

**Q42) Write a Pandas program to count the number of unique values in cut series of diamonds DataFrame.**

In [ ]:
# Write your code here
# Count the number of unique values in the 'cut' series
unique_cut_count = diamonds['cut'].nunique()

# Print the number of unique values in the 'cut' series
unique_cut_count

5

**Q43) Write a Pandas program to check the number of rows and columns and drop those row if 'any' values are missing in a row of diamonds DataFrame.**

In [ ]:
# Write your code here

# Check the number of rows and columns in the DataFrame
num_rows, num_cols = diamonds.shape
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)

# Drop rows with any missing values
diamonds_dropped = diamonds.dropna()

# Check the number of rows and columns after dropping missing values
num_rows_dropped, num_cols_dropped = diamonds_dropped.shape
print("Number of rows after dropping missing values:", num_rows_dropped)
print("Number of columns after dropping missing values:", num_cols_dropped)

Number of rows: 53940
Number of columns: 11
Number of rows after dropping missing values: 53940
Number of columns after dropping missing values: 11

**Q44) Write a Pandas program to set an existing column as the index of diamonds DataFrame and restore the index name, and move the index back to a column.**

In [ ]:
# Write your code here
# Set the 'carat' column as the index of the DataFrame
diamonds.set_index('carat', inplace=True)

# Print the DataFrame with 'carat' as the index
print(diamonds)

# Restore the index name
diamonds.index.name = 'carat_index'

# Print the DataFrame with restored index name
print(diamonds)

# Move the index back to a column
diamonds.reset_index(inplace=True)

# Print the DataFrame with 'carat' as a column again
diamonds

KeyError: ignored

**Q45) Write a Pandas program to calculate the multiply of length, width and depth for each cut of diamonds DataFrame.**

In [ ]:
# Write your code here

# Calculate the product of length, width, and depth for each cut category
diamonds['volume'] = diamonds['x'] * diamonds['y'] * diamonds['z']

# Print the DataFrame with the new 'volume' column
diamonds

,carat_index,cut,color,clarity,depth,table,price,x,y,z,Quality - color,volume
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal - E,38.202030
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium - E,34.505856
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good - E,38.076885
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium - I,46.724580
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good - J,51.917250
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal - D,115.920000
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good - D,118.110175
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good - D,114.449728
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium - H,140.766120
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal - D,124.568444

**Q46) Write a Pandas program to concatenate the diamonds DataFrame with the 'color' Series.**

In [ ]:
# Write your code here
# Create a new Series for 'color'
color_series = diamonds['color']

# Concatenate the diamonds DataFrame with the 'color' Series along the columns (axis=1)
concatenated_df = pd.concat([diamonds, color_series], axis=1)

# Print the concatenated DataFrame
concatenated_df

,carat_index,cut,color,clarity,depth,table,price,x,y,z,Quality - color,volume,color
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal - E,38.202030,E
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium - E,34.505856,E
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good - E,38.076885,E
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium - I,46.724580,I
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good - J,51.917250,J
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal - D,115.920000,D
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good - D,118.110175,D
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good - D,114.449728,D
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium - H,140.766120,H
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal - D,124.568444,D

**Q47) Write a Pandas program to read rows in which the ‘cut’ is ‘Premium’, column ‘color’ of diamonds DataFrame.**

In [ ]:
# Write your code here
# Filter rows with 'cut' as 'Premium' and select only the 'color' column
premium_color_df = diamonds.loc[diamonds['cut'] == 'Premium', ['color']]

# Print the resulting DataFrame
premium_color_df

      color
1         E
3         I
12        F
14        E
15        E
...     ...
53928     E
53930     E
53931     F
53934     D
53938     H

[13791 rows x 1 columns]

**Q48) Write a Pandas program to calculate the memory usage for each Series (in bytes) of diamonds DataFrame.**

In [ ]:
# Write your code here


# Calculate memory usage for each Series (column)
memory_usage_df = pd.DataFrame({'Memory Usage (bytes)': diamonds.memory_usage(deep=True)})

# Print the memory usage for each Series (column)
memory_usage_df

                 Memory Usage (bytes)
Index                             128
carat_index                    431520
cut                           3413674
color                         3128520
clarity                       3242590
depth                          431520
table                          431520
price                          431520
x                              431520
y                              431520
z                              431520
Quality - color               3629434
volume                         431520

**Q49) Write a Pandas program to get sample 75% of the diamonds DataFrame's rows without replacement and store the remaining 25% of the rows in another DataFrame.**

In [ ]:
# Write your code here
# Get a sample of 75% of the rows without replacement
sampled_df = diamonds.sample(frac=0.75, random_state=42)

# Store the remaining 25% of rows in another DataFrame
remaining_df = diamonds.drop(sampled_df.index)

# Print the sampled DataFrame (75% of rows)
print("Sampled DataFrame (75% of rows):\n")
sampled_df

Sampled DataFrame (75% of rows):

,carat_index,cut,color,clarity,depth,table,price,x,y,z,Quality - color,volume
1388,0.24,Ideal,G,VVS1,62.1,56.0,559,3.97,4.00,2.47,Ideal - G,39.223600
50052,0.58,Very Good,F,VVS2,60.0,57.0,2201,5.44,5.42,3.26,Very Good - F,96.120448
41645,0.40,Ideal,E,VVS2,62.1,55.0,1238,4.76,4.74,2.95,Ideal - E,66.559080
42377,0.43,Premium,E,VVS2,60.8,57.0,1304,4.92,4.89,2.98,Premium - E,71.695224
17244,1.55,Ideal,E,SI2,62.3,55.0,6901,7.44,7.37,4.61,Ideal - E,252.779208
...,...,...,...,...,...,...,...,...,...,...,...,...
48565,0.50,Good,G,VVS2,64.4,57.0,1991,4.97,5.05,3.22,Good - G,80.817170
12312,1.24,Ideal,I,SI2,61.9,57.0,5221,6.87,6.92,4.27,Ideal - I,202.997508
18130,1.51,Premium,H,SI2,60.2,62.0,7340,7.43,7.38,4.46,Premium - H,244.556964
39846,0.51,Very Good,F,SI2,62.7,56.0,1100,5.07,5.10,3.19,Very Good - F,82.483830
9114,1.02,Very Good,I,VS2,59.3,59.0,4532,6.56,6.60,3.90,Very Good - I,168.854400

In [ ]:
# Print the remaining DataFrame (25% of rows)
print("\nRemaining DataFrame (25% of rows):\n")
remaining_df

Remaining DataFrame (25% of rows):

,carat_index,cut,color,clarity,depth,table,price,x,y,z,Quality - color,volume
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good - E,38.076885
9,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39,Very Good - H,38.718000
10,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73,Good - J,49.658700
12,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33,Premium - F,34.715136
16,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68,Ideal - I,50.130472
...,...,...,...,...,...,...,...,...,...,...,...,...
53921,0.70,Very Good,E,VS2,62.8,60.0,2755,5.59,5.65,3.53,Very Good - E,111.489755
53925,0.79,Ideal,I,SI1,61.6,56.0,2756,5.95,5.97,3.67,Ideal - I,130.363905
53930,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49,Premium - E,115.988754
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal - D,115.920000
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good - D,114.449728

**Q50) Write a Pandas program to read the diamonds DataFrame and detect duplicate color.**

**Note:** duplicated () function returns boolean Series denoting duplicate rows, optionally only considering certain columns.

In [ ]:
# Write your code here

# Detect duplicate colors in the 'color' column
duplicate_colors = diamonds.duplicated(subset='color', keep=False)

# Filter the DataFrame to show only the duplicate rows based on color
duplicate_rows = diamonds[duplicate_colors]

# Print the duplicate rows based on color
duplicate_rows

,carat_index,cut,color,clarity,depth,table,price,x,y,z,Quality - color,volume
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,Ideal - E,38.202030
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,Premium - E,34.505856
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,Good - E,38.076885
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,Premium - I,46.724580
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,Good - J,51.917250
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,Ideal - D,115.920000
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,Good - D,118.110175
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,Very Good - D,114.449728
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,Premium - H,140.766120
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,Ideal - D,124.568444